name: 'airbyte_google_ads'
version: '0.1.0'
require-dbt-version: ['>=1.0.0']
config-version: 2
profile: 'default'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  airbyte_google_ads:
    materialized: table
    intermediate:
      materialized: ephemeral

vars:
  airbyte_google_ads:
    campaigns: "{{ source('airbyte_google_ads','campaigns')}}"
    ad_groups: "{{ source('airbyte_google_ads','ad_groups')}}"
    ad_group_ad_report: "{{ source('airbyte_google_ads','ad_group_ad_report')}}"
    
