
version: 2

sources:
  - name: airbyte_google_ads
    schema: "{{ var('google_ads_schema', 'google_ads') }}"
    database: "{% if target.type != 'spark'%}{{ var('google_ads_database', target.database) }}{% endif %}"
    tables:
      - name: campaigns
      - name: ad_group_ad_report
      - name: click_view
      - name: keyword_report

models:
  - name: google_ads__campaign_history
    description: "A table storing historical campaign statistics."
    columns:
      - name: campaign_id
        description: "The unique identifier for the campaign"
        tests:
          - not_null
      - name: campaign_name
        description: "The name of the campaign"
        tests:
          - not_null
      - name: status
        description: "The status of the campaign"
        tests:
          - not_null  
      - name: start_date
        description: "The date the campaign started"
        tests: 
          - not_null
      - name: end_date
        description: "The date the campaign ended"
        tests:
          - not_null
      - name: has_content_network
        description: "A flag indicating whether the content network is enabled"
        tests:
          - not_null
      - name: has_google_search
        description: "A flag indicating whether Google search is enabled"
        tests:
        - not_null
      - name: has_search_network
        description: "A flag indicating whether search network is enabled"
        tests:
        - not_null
      - name: has_partner_search_network
        description: "A flag indicating whether partner search network is enabled"
        tests:
        - not_null
      - name: clicks
        description: "The number of clicks on ads part of this campaign"
        tests:
        - not_null
      - name: impressions
        description: "The number of impressions on ads part of this campaign"
        tests:
        - not_null
      - name: cost
        description: "The total cost incurred by this campaign"
        tests:
        - not_null
      
  - name: google_ads__ad_group_history
    description: "A table storing historical ad set statistics."
    columns:
      - name: ad_group_id
        description: "The unique identifier for the ad set"
        tests:
          - not_null
      - name: campaign_id
        description: "The unique identifier for the campaign"
        tests:
          - not_null
      - name: ad_group_name
        description: "The name of the ad group"
        tests:
          - not_null
      - name: campaign_name
        description: "The name of the ad campaign"
        tests:
          - not_null
      - name: status
        description: "The status of the ad group"
        tests:
          - not_null
      - name: date
        description: "The date the metrics were recorded"
        tests: 
          - not_null
      - name: clicks
        description: "The number of clicks on ads part of this ad group"
        tests:
        - not_null
      - name: impressions
        description: "The number of impressions on ads part of this ad group"
        tests:
        - not_null
      - name: engagements
        description: "The number of engagements on ads part of this ad group"
        tests:
        - not_null
      - name: interactions
        description: "The number of interactions on ads part of this ad group"
        tests:
        - not_null
      - name: conversions
        description: "The number of conversions on ads part of this ad group"
        tests:
        - not_null
      - name: view_through_conversions
        description: "The number of view through conversions on ads part of this ad group"
        tests:
        - not_null
      - name: conversions_value
        description: "The total revenue generated by ads part of this ad group"
        tests:
        - not_null
      - name: cost
        description: "The total cost incurred by this ad group"
        tests:
        - not_null
  - name: google_ads__click_performance
    description: "A table storing information about clicks on google ads."
    columns:
      - name: ad_group_id
        description: "The unique identifier for the ad group"
        tests:
          - not_null
      - name: campaign_id
        description: "The unique identifier for the campaign"
        tests:
          - not_null
          - relationships:
              to: ref('google_ads__campaign_history')
              field: campaign_id
      - name: date
        description: "The date the click happened"
        tests:
          - not_null
      - name: gclid
        description: "The unique identifier of the google ad click"
        tests:
          - not_null
      - name: ad_network_type
        description: "The type of ad network that generated the click"
        tests:
          - not_null
          - accepted_values: 
              values: ["SEARCH", "SEARCH_PARTNERS", "MIXED", "CONTENT"]
      - name: keyword
        description: "The keyword that was used to generate the click"
        tests:
          - not_null
  - name: google_ads__keywords
    description: "A table storing information about keywords on your google ads."
    columns:
      - name: ad_group_id
        description: "The unique identifier for the ad group"
        tests:
          - not_null
          - relationships:
              to: ref('google_ads__ad_group_history')
              field: ad_group_id
      - name: date
        description: "The date the click happened"
        tests:
          - not_null
      - name: keyword
        description: "The keyword that was used to generate the click"
        tests:
          - not_null
      - name: match_type
        description: "The match type of the keyword"
        tests:
          - not_null
          - accepted_values: 
              values: ["EXACT", "BROAD", "PHRASE"]
      - name: cost
        description: "The cost of the keyword in the ad group"
        tests:
          - not_null
      - name: impressions
        description: "The number of impressions of the keyword"
        tests:
          - not_null
      - name: ctr
        description: "The click through rate of the keyword"
        tests:
          - not_null

metrics:
  - name: total_number_of_impressions
    label: Total Number of Impressions
    model: ref('google_ads__campaign_history')
    description: "The number of impressions generated by the campaign"

    type: sum
    sql: impressions

    timestamp: date
    time_grains: [day, week, month]

    dimensions:
      - status
      - channel_type
      - campaign_name

  - name: total_number_of_clicks
    label: Total Number of Clicks
    model: ref('google_ads__campaign_history')
    description: "The number of clicks generated by the campaign"

    type: sum
    sql: clicks

    timestamp: date
    time_grains: [day, week, month]

    dimensions:
      - status
      - channel_type
      - campaign_name

  - name: total_number_of_video_views
    label: Total Number of Video Views
    model: ref('google_ads__campaign_history')
    description: "The number of video views generated by the campaign"

    type: sum
    sql: video_views

    timestamp: date
    time_grains: [day, week, month]

    dimensions:
      - status
      - channel_type
      - campaign_name

  - name: total_campaign_cost
    label: Total Cost of Campaign
    model: ref('google_ads__campaign_history')
    description: "The cost of the campaign"

    type: sum
    sql: cost

    timestamp: date
    time_grains: [day, week, month]

    dimensions:
      - status
      - channel_type
      - campaign_name

  - name: total_campaign_interactions
    label: Total Campaign Interactions
    model: ref('google_ads__campaign_history')
    description: "The total number of interactions for a campaign"

    type: sum
    sql: interactions

    timestamp: date
    time_grains: [day, week, month]

    dimensions:
      - status
      - channel_type
      - campaign_name

  - name: total_campaign_conversions
    label: Total Conversions of Campaign
    model: ref('google_ads__campaign_history')
    description: "The total number of conversions for a campaign"

    type: sum
    sql: conversions

    timestamp: date
    time_grains: [day, week, month]

    dimensions:
      - status
      - channel_type
      - campaign_name

  - name: total_campaign_view_through_conversions
    label: Total View Through Conversions of Campaign
    model: ref('google_ads__campaign_history')
    description: "The total number of view through conversions for a campaign"

    type: sum
    sql: view_through_conversions

    timestamp: date
    time_grains: [day, week, month]

    dimensions:
      - status
      - channel_type
      - campaign_name

  - name: total_campaign_conversion_value
    label: Total Value of Campaign Conversions
    model: ref('google_ads__campaign_history')
    description: "The total value of conversions for a campaign"

    type: sum
    sql: conversions_value

    timestamp: date
    time_grains: [day, week, month]

    dimensions:
      - status
      - channel_type
      - campaign_name

  - name: total_keyword_impressions
    label: Total Keyword Impressions
    model: ref('google_ads__keywords')
    description: "The total number of impressions for a given keyword"

    type: sum
    sql: impressions

    timestamp: date
    time_grains: [day, week, month]

    dimensions:
      - keyword
      - match_type

  - name: total_keyword_cost
    label: Total Keyword Cost
    model: ref('google_ads__keywords')
    description: "The total cost for keyword impressions"

    type: sum
    sql: cost

    timestamp: date
    time_grains: [day, week, month]

    dimensions:
      - keyword
      - match_type

  - name: average_clickthrough_rate
    label: Average Clickthrough Rate
    model: ref('google_ads__keywords')
    description: "The average clickthrough rate for a keyword"

    type: average
    sql: ctr

    timestamp: date
    time_grains: [day, week, month]

    dimensions:
      - keyword
      - match_type